// Code generated by candi v1.11.5.

package domain

import "github.com/golangid/candi/candishared"

// FilterProducts model
type FilterProducts struct {
	candishared.Filter
	ID  int
	Sku string `json:"sku,omitempty"`
}
