// Code generated by candi v1.11.5.

package repository

import (
	"context"
	"database/sql"
	"fmt"

	// @candi:repositoryImport
	itemsrepo "kuncie/internal/modules/items/repository"
	ordersrepo "kuncie/internal/modules/orders/repository"
	productsrepo "kuncie/internal/modules/products/repository"

	"github.com/golangid/candi/candishared"
	"github.com/golangid/candi/tracer"

	"kuncie/pkg/shared"

	"gorm.io/driver/postgres"
	"gorm.io/gorm"
)

type (
	// RepoSQL abstraction
	RepoSQL interface {
		WithTransaction(ctx context.Context, txFunc func(ctx context.Context) error) (err error)

		// @candi:repositoryMethod
		ItemsRepo() itemsrepo.ItemsRepository
		OrdersRepo() ordersrepo.OrdersRepository
		ProductsRepo() productsrepo.ProductsRepository
	}

	repoSQLImpl struct {
		readDB, writeDB *gorm.DB

		// register all repository from modules
		// @candi:repositoryField
		itemsRepo    itemsrepo.ItemsRepository
		ordersRepo   ordersrepo.OrdersRepository
		productsRepo productsrepo.ProductsRepository
	}
)

var (
	globalRepoSQL RepoSQL
)

// setSharedRepoSQL set the global singleton "RepoSQL" implementation
func setSharedRepoSQL(readDB, writeDB *sql.DB) {
	gormRead, err := gorm.Open(postgres.New(postgres.Config{
		Conn: readDB,
	}), &gorm.Config{})
	if err != nil {
		panic(err)
	}

	gormWrite, err := gorm.Open(postgres.New(postgres.Config{
		Conn: writeDB,
	}), &gorm.Config{SkipDefaultTransaction: true})
	if err != nil {
		panic(err)
	}

	shared.AddGormCallbacks(gormRead)
	shared.AddGormCallbacks(gormWrite)

	globalRepoSQL = NewRepositorySQL(gormRead, gormWrite)
}

// GetSharedRepoSQL returns the global singleton "RepoSQL" implementation
func GetSharedRepoSQL() RepoSQL {
	return globalRepoSQL
}

// NewRepositorySQL constructor
func NewRepositorySQL(readDB, writeDB *gorm.DB) RepoSQL {

	return &repoSQLImpl{
		readDB: readDB, writeDB: writeDB,

		// @candi:repositoryConstructor
		itemsRepo:    itemsrepo.NewItemsRepoSQL(readDB, writeDB),
		ordersRepo:   ordersrepo.NewOrdersRepoSQL(readDB, writeDB),
		productsRepo: productsrepo.NewProductsRepoSQL(readDB, writeDB),
	}
}

// WithTransaction run transaction for each repository with context, include handle canceled or timeout context
func (r *repoSQLImpl) WithTransaction(ctx context.Context, txFunc func(ctx context.Context) error) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "RepoSQL:Transaction")
	defer trace.Finish()

	tx := r.writeDB.Begin()
	err = tx.Error
	if err != nil {
		return err
	}

	defer func() {
		if err != nil {
			tx.Rollback()
			trace.SetError(err)
		} else {
			tx.Commit()
		}
	}()

	errChan := make(chan error)
	go func(ctx context.Context) {
		defer func() {
			if r := recover(); r != nil {
				errChan <- fmt.Errorf("panic: %v", r)
			}
			close(errChan)
		}()

		if err := txFunc(ctx); err != nil {
			errChan <- err
		}
	}(candishared.SetToContext(ctx, candishared.ContextKeySQLTransaction, tx))

	select {
	case <-ctx.Done():
		return fmt.Errorf("Canceled or timeout: %v", ctx.Err())
	case e := <-errChan:
		return e
	}
}

func (r *repoSQLImpl) ItemsRepo() itemsrepo.ItemsRepository {
	return r.itemsRepo
}

func (r *repoSQLImpl) OrdersRepo() ordersrepo.OrdersRepository {
	return r.ordersRepo
}

func (r *repoSQLImpl) ProductsRepo() productsrepo.ProductsRepository {
	return r.productsRepo
}
