// Code generated by candi v1.11.5.

package repository

import (
	"context"

	"kuncie/internal/modules/products/domain"
	shareddomain "kuncie/pkg/shared/domain"
)

// ProductsRepository abstract interface
type ProductsRepository interface {
	Find(ctx context.Context, filter *domain.FilterProducts) (shareddomain.Products, error)
	Save(ctx context.Context, data *shareddomain.Products) error
}
