// Code generated by candi v1.11.5.

package common

import (
	"context"
	shareddomain "kuncie/pkg/shared/domain"
)

var commonUC Usecase

// Usecase common abstraction for bridging shared method inter usecase in module
type Usecase interface {
	// shared method from another usecase
	Promotions(ctx context.Context, sku string, qty int) (data []shareddomain.Products, err error)
	UpdateProducts(ctx context.Context, sku string, data *shareddomain.Products) (err error)
}

// SetCommonUsecase constructor
func SetCommonUsecase(uc Usecase) Usecase {
	commonUC = uc
	return commonUC
}

// GetCommonUsecase get common usecase
func GetCommonUsecase() Usecase {
	return commonUC
}
